Frank/storybook dev env/core 2668 (#1965)
* ci: storybook preview support

* ci: add storybook deploy stages

* ci: fix dependency

* ci: fix step name

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -238,11 +238,14 @@ jobs:
           target: "statefulset/creator-app"
           tagged: << parameters.tagged >>
 
-  build-deploy-storybook-image:
+  build-deploy-storybook-dev-environment:
     executor: vfcommon/build-executor
     environment:
       IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook"
     steps:
+      - add_ssh_keys: # To enable write access to repository for removing dev environment branches
+          fingerprints:
+            - "93:f8:51:53:5e:bd:75:0e:29:24:4d:6a:3f:ef:e1:4a"
       - attach_workspace:
           at: /tmp/vf-build
       - setup_remote_docker
@@ -261,8 +264,48 @@ jobs:
             IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
             $(aws ecr get-login --no-include-email --region us-east-1)
             docker push $IMAGE_NAME
-            docker tag $IMAGE_NAME $IMAGE_REPO:latest-$CIRCLE_BRANCH
-            docker push $IMAGE_REPO:latest-$CIRCLE_BRANCH
+      - run:
+          name: Install latest envcli utility
+          command: |
+            API_URL="https://$GITHUB_TOKEN:@api.github.com/repos/voiceflow/envcli"
+            ASSET_ID=$(curl $API_URL/releases/latest | jq -r '.assets[2].id')
+            curl -J -L -H "Accept: application/octet-stream" "$API_URL/releases/assets/$ASSET_ID" --output envcli.tar.gz
+            tar -xf envcli.tar.gz
+      - run:
+          name: "Deploy dev environment image"
+          command: |
+            IMAGE_TAG="k8s-$CIRCLE_SHA1"
+            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
+            ENV_NAME="${CIRCLE_BRANCH%%_*}"
+            aws eks --region us-east-1 update-kubeconfig --name development
+            NON_INTERACTIVE=true ./envcli edit component storybook storybook -n $ENV_NAME -i $IMAGE_NAME
+
+  build-deploy-storybook-image:
+    executor: vfcommon/build-executor
+    environment:
+      IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook"
+    steps:
+      - attach_workspace:
+          at: /tmp/vf-build
+      - setup_remote_docker
+      - run:
+          name: "Build and push dev environment image"
+          command: |
+            IMAGE_TAG="k8s-$CIRCLE_SHA1"
+            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
+            $(aws ecr get-login --no-include-email --region us-east-1)
+            set +e
+            DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $IMAGE_NAME > /dev/null 2>&1
+            SEARCH_IMAGE_RESULT=$?
+            set -e
+            if [[ $SEARCH_IMAGE_RESULT -ne 0 ]]; then   # Only build the image if there are no existing images 
+              docker build \
+                -f storybook.dockerfile \
+                -t $IMAGE_NAME .
+              $(aws ecr get-login --no-include-email --region us-east-1)
+              docker push $IMAGE_NAME
+            fi
+            git push origin --delete $CIRCLE_BRANCH --no-verify # Clean up branch
       - run:
           name: Update image
           command: |
@@ -424,6 +467,21 @@ workflows:
           context: dev-test
           requires:
             - build-app-dev-environment
+          filters:
+            branches:
+              only:
+                - /env-.*/
+
+      - build-storybook:
+          context: dev-test
+          filters:
+            branches:
+              only:
+                - /env-.*/
+      - build-deploy-storybook-dev-environment:
+          context: dev-test
+          requires:
+            - build-storybook
           filters:
             branches:
               only:
